repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      exclude: ".*execution_engine2Impl.py"
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
