
dist: xenial
sudo: required
language: python
install:
  - pip install -r requirements.txt

services:
  - docker
  - mongodb

env:
  global: # The following are for the dockerhub DOCKER_USER and DOCKER_PASS env vars used in the push script
    - secure: "GEbQy4zR5hhHDzjoThGyCHZVmpEWKduwR/sZ1sR8csOYrfYqQTHinhAMY+KAdUhjJfWGwR9l2v2xkhyokzdADhKOqZJo7jkkioPEtENdocTWMYq7Qedg6kUCzcAutURIBCcoJtW4vrpGZ+1YR4vB8BhA11KA62QUbsQY3ds/LTg="
    - secure: "NbHt1OUyrTXmN+tYAFcGH3mxlxraDKJ6WQNTJTG+u+wTOzh2MU1bf59l+oanvqlydpd7ZzG7c2cUpje5hvBMEV9s9jwdWqTlGXHWpcU3a1wZdNOkkAPK0Cb3opabRLwIqjovaoAAouSJCq/jUADzhusjrZcn5JVA7sSpYyJT3uE="

# command to run tests
# TODO: Save a dockerhub image and use that instead of building it each time?


before_install:
  - sudo useradd kbase
  - sleep 15
  - mongo ee2 --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'


script:
  - chmod +x ./build/build_docker_image.sh && chmod +x ./build/push2dockerhub.sh
  - make test-with-docker
  # - make integration_test Doesn't yet work in travis



after_success:
 # Need to set up credentials for this
 - make build-docker-image
 #  - IMAGE_NAME=kbase/ee2 ./build/push2dockerhub.sh
 - codecov
