language: python
python:
  - "3.7"

dist: xenial
sudo: required

services:
  - docker

env:
  - KB_DEPLOYMENT_CONFIG=test/deploy.cfg

before_install:
  - sudo useradd kbase
  - (cd test/dockerfiles/condor && docker-compose up -d)
  - cp test/env/test.travis.env test/env/test.env


install:
  - pip install -r requirements.txt
  - pip install black flake8
  - flake8 ./lib ./test
  - black --check ./lib ./test
  - make setup-database

script:
  - make test-coverage
  # - make integration_test Doesn't yet work in travis

after_success:
 # Need to set up credentials for this
 # - make build-docker-image #Maybe deprecate this for quay?
 #  - IMAGE_NAME=kbase/ee2 ./build/push2dockerhub.sh
 - codecov
