language: python
python:
  - "3.7"

dist: xenial
sudo: required



services:
  - docker


env:
  global: # The following are for the dockerhub DOCKER_USER and DOCKER_PASS env vars used in the push script
    - secure: "GEbQy4zR5hhHDzjoThGyCHZVmpEWKduwR/sZ1sR8csOYrfYqQTHinhAMY+KAdUhjJfWGwR9l2v2xkhyokzdADhKOqZJo7jkkioPEtENdocTWMYq7Qedg6kUCzcAutURIBCcoJtW4vrpGZ+1YR4vB8BhA11KA62QUbsQY3ds/LTg="
    - secure: "NbHt1OUyrTXmN+tYAFcGH3mxlxraDKJ6WQNTJTG+u+wTOzh2MU1bf59l+oanvqlydpd7ZzG7c2cUpje5hvBMEV9s9jwdWqTlGXHWpcU3a1wZdNOkkAPK0Cb3opabRLwIqjovaoAAouSJCq/jUADzhusjrZcn5JVA7sSpYyJT3uE="

# command to run tests
# TODO: Save a dockerhub image and use that instead of building it each time?


before_install:
  - sudo useradd kbase
  - (cd test/dockerfiles/condor && docker-compose up -d)
  - chmod +x ./build/build_docker_image.sh && chmod +x ./build/push2dockerhub.sh
  - cp test/env/test.travis.env test/env/test.env


install:
  - pip install -r requirements.txt
  - make setup-database


script:
  - make test
  - make test-models
  # - make integration_test Doesn't yet work in travis

after_success:
 # Need to set up credentials for this
 - make build-docker-image
 #  - IMAGE_NAME=kbase/ee2 ./build/push2dockerhub.sh
 - codecov
