[tool.black]
include = '\.pyi?$'

exclude = '''
(
 /(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
 )/
  | execution_engine2Impl.py # also separately exclude a file named impl.py in
                     # the root of the project
)
'''
