[tool.black]
include = '\.pyi?$'

exclude = '''
(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | __pycache__
  | lib/__pycache__
  | lib/execution_engine2/execution_engine2Impl.py
  | lib/execution_engine2/authclient.py
  | lib/biokbase/log.py
  | lib/installed_clients/*
)
'''
