name: Build Develop/Master

on:
  pull_request:
    branches: [master,develop]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -       
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ee2:latest

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
