name: Build Main/Develop Branches

on:
  push:
    branches: 
      - main
      - master
      - develop

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -       
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push the main branch
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref }}

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
