# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# To ssh into this build add the following:
#- name: Start SSH session
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
#        SSH_PASS: ${{ secrets.SSH_PASS }}

name: Execution Engine 2 Test Suite

on:
  [pull_request]

jobs:
  lint_with_black:	
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./lib"      
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./test"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        flake8 ./lib ./test
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements-dev.txt; fi
        cd /opt
        git clone https://github.com/kbase/jars
        cd -
    - name: Build Docker Image
      run: |
        docker build . -t execution_engine2:test
    - name: Run Tests
      run: |
        docker-compose up -d
        cp test/env/test.travis.env test.env
        make test-coverage
        codecov

